"""
Tipologias de empreendimento — banco de presets.
Traduzido do JS TIPOLOGIAS constant (viabilidade.js lines 1-117).
"""

TIPOLOGIAS = {
    "condhoriz": {
        "label": "Condomínio Horizontal",
        "cliente": "xxxx",
        "obra": "Condomínio xxxxx",
        "local": "São Luís — MA",
        "cub": 2096.27,
        "terreno": 1500000,
        "qtdApts": 14,
        "areaApt": 120,
        "precoMercado": 8617,
        "areas": [
            {"nome": "Casas Residenciais",  "qtd": 14, "area": 120,    "equiv": 1.00},
            {"nome": "Portaria",            "qtd": 1,  "area": 33.99,  "equiv": 1.00},
            {"nome": "Estacionamento",      "qtd": 1,  "area": 100,    "equiv": 0.10},
            {"nome": "Lixeira",             "qtd": 1,  "area": 31.95,  "equiv": 0.75},
            {"nome": "Área de Lazer",       "qtd": 1,  "area": 444.05, "equiv": 0.50},
            {"nome": "Reservatório",        "qtd": 1,  "area": 64.20,  "equiv": 0.50},
        ],
        "indiretos": [
            {"nome": "Adm. central",              "pct": 2.0},
            {"nome": "Adm. local",                "pct": 3.5},
            {"nome": "Mobilização/desmob.",        "pct": 1.5},
            {"nome": "Despesas financeiras",       "pct": 1.5},
            {"nome": "Riscos e eventuais",         "pct": 1.5},
            {"nome": "Mov. de terra",              "pct": 4.0},
            {"nome": "Projetos (arq/est/inst)",    "pct": 4.0},
        ],
        "impostos": [
            {"nome": "PIS",             "pct": 0.65, "tipo": "imposto"},
            {"nome": "COFINS",          "pct": 3.0,  "tipo": "imposto"},
            {"nome": "ISS",             "pct": 5.0,  "tipo": "imposto"},
            {"nome": "IRPJ",            "pct": 1.2,  "tipo": "imposto"},
            {"nome": "CSLL",            "pct": 1.08, "tipo": "imposto"},
            {"nome": "Corretagem",      "pct": 6.0,  "tipo": "corretagem"},
            {"nome": "Lucro requerido", "pct": 35.0, "tipo": "lucro"},
        ],
    },
    "vertical": {
        "label": "Edifício Residencial Vertical",
        "cliente": "",
        "obra": "Residencial Alto",
        "local": "São Luís — MA",
        "cub": 1866.08,
        "terreno": 2000000,
        "qtdApts": 32,
        "areaApt": 80,
        "precoMercado": 8617,
        "areas": [
            {"nome": "Apartamentos (8 pav × 4 apts)", "qtd": 32, "area": 80,  "equiv": 1.00},
            {"nome": "Hall/Circulação",                "qtd": 8,  "area": 40,  "equiv": 0.50},
            {"nome": "Garagem coberta",                "qtd": 32, "area": 12.5,"equiv": 0.50},
            {"nome": "Área de lazer",                  "qtd": 1,  "area": 300, "equiv": 0.50},
            {"nome": "Reservatório/Casa de máq.",       "qtd": 1,  "area": 60,  "equiv": 0.50},
        ],
        "indiretos": [
            {"nome": "Adm. central",          "pct": 2.0},
            {"nome": "Adm. local",            "pct": 4.0},
            {"nome": "Mobilização/desmob.",    "pct": 1.0},
            {"nome": "Despesas financeiras",   "pct": 2.0},
            {"nome": "Riscos e eventuais",     "pct": 1.5},
            {"nome": "Projetos",               "pct": 5.0},
            {"nome": "Elevadores (excl. CUB)", "pct": 3.0},
        ],
        "impostos": [
            {"nome": "PIS",             "pct": 0.65, "tipo": "imposto"},
            {"nome": "COFINS",          "pct": 3.0,  "tipo": "imposto"},
            {"nome": "ISS",             "pct": 5.0,  "tipo": "imposto"},
            {"nome": "IRPJ",            "pct": 1.2,  "tipo": "imposto"},
            {"nome": "CSLL",            "pct": 1.08, "tipo": "imposto"},
            {"nome": "Corretagem",      "pct": 6.0,  "tipo": "corretagem"},
            {"nome": "Lucro requerido", "pct": 20.0, "tipo": "lucro"},
        ],
    },
    "mcmv": {
        "label": "MCMV / Habitação de Interesse Social",
        "cliente": "",
        "obra": "Residencial Popular",
        "local": "São Luís — MA",
        "cub": 1915.89,
        "terreno": 500000,
        "qtdApts": 48,
        "areaApt": 48,
        "precoMercado": 4500,
        "areas": [
            {"nome": "Apartamentos HIS",         "qtd": 48, "area": 48, "equiv": 1.00},
            {"nome": "Circulação/Hall",           "qtd": 4,  "area": 30, "equiv": 0.50},
            {"nome": "Estacionamento descoberto", "qtd": 24, "area": 12, "equiv": 0.10},
        ],
        "indiretos": [
            {"nome": "Adm. central",        "pct": 1.5},
            {"nome": "Adm. local",          "pct": 3.0},
            {"nome": "Mobilização/desmob.", "pct": 0.5},
            {"nome": "Riscos e eventuais",  "pct": 1.0},
            {"nome": "Projetos",            "pct": 3.0},
        ],
        "impostos": [
            {"nome": "PIS (RET MCMV)",  "pct": 0.50, "tipo": "imposto"},
            {"nome": "COFINS (RET MCMV)","pct": 0.50, "tipo": "imposto"},
            {"nome": "ISS",              "pct": 3.0,  "tipo": "imposto"},
            {"nome": "IRPJ (RET)",       "pct": 0.29, "tipo": "imposto"},
            {"nome": "CSLL (RET)",       "pct": 0.26, "tipo": "imposto"},
            {"nome": "Corretagem",       "pct": 4.0,  "tipo": "corretagem"},
            {"nome": "Lucro requerido",  "pct": 12.0, "tipo": "lucro"},
        ],
    },
    "comercial": {
        "label": "Comercial / Sala e Loja",
        "cliente": "",
        "obra": "Centro Comercial",
        "local": "São Luís — MA",
        "cub": 1866.82,
        "terreno": 1200000,
        "qtdApts": 20,
        "areaApt": 60,
        "precoMercado": 7000,
        "areas": [
            {"nome": "Salas comerciais", "qtd": 20, "area": 60,  "equiv": 1.00},
            {"nome": "Lojas térreas",    "qtd": 4,  "area": 80,  "equiv": 1.00},
            {"nome": "Circulação/Hall",  "qtd": 1,  "area": 200, "equiv": 0.50},
            {"nome": "Estacionamento",   "qtd": 24, "area": 13,  "equiv": 0.50},
        ],
        "indiretos": [
            {"nome": "Adm. central",        "pct": 2.0},
            {"nome": "Adm. local",          "pct": 4.0},
            {"nome": "Despesas financeiras","pct": 2.0},
            {"nome": "Riscos e eventuais",  "pct": 1.5},
            {"nome": "Projetos especiais",  "pct": 5.0},
        ],
        "impostos": [
            {"nome": "PIS",             "pct": 0.65, "tipo": "imposto"},
            {"nome": "COFINS",          "pct": 3.0,  "tipo": "imposto"},
            {"nome": "ISS",             "pct": 5.0,  "tipo": "imposto"},
            {"nome": "IRPJ",            "pct": 1.2,  "tipo": "imposto"},
            {"nome": "CSLL",            "pct": 1.08, "tipo": "imposto"},
            {"nome": "Corretagem",      "pct": 6.0,  "tipo": "corretagem"},
            {"nome": "Lucro requerido", "pct": 25.0, "tipo": "lucro"},
        ],
    },
    "custom": {
        "label": "Personalizado",
        "cliente": "",
        "obra": "Meu Empreendimento",
        "local": "",
        "cub": 2096.27,
        "terreno": 500000,
        "qtdApts": 10,
        "areaApt": 100,
        "precoMercado": 8617,
        "areas": [
            {"nome": "Área principal", "qtd": 10, "area": 100, "equiv": 1.00},
        ],
        "indiretos": [
            {"nome": "Adm. central",       "pct": 2.0},
            {"nome": "Adm. local",         "pct": 3.5},
            {"nome": "Projetos",           "pct": 4.0},
            {"nome": "Riscos e eventuais", "pct": 1.5},
        ],
        "impostos": [
            {"nome": "PIS",             "pct": 0.65, "tipo": "imposto"},
            {"nome": "COFINS",          "pct": 3.0,  "tipo": "imposto"},
            {"nome": "ISS",             "pct": 5.0,  "tipo": "imposto"},
            {"nome": "IRPJ",            "pct": 1.2,  "tipo": "imposto"},
            {"nome": "CSLL",            "pct": 1.08, "tipo": "imposto"},
            {"nome": "Corretagem",      "pct": 6.0,  "tipo": "corretagem"},
            {"nome": "Lucro requerido", "pct": 20.0, "tipo": "lucro"},
        ],
    },
}
